server:
  port: 8055
  servlet:
    context-path: /api

spring:
  application:
    name: cloud-job
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.49:8848
        namespace: d685bf52-93ce-4271-942b-688f25725547

  datasource:
    druid:
      url: "${DB_URL:jdbc:mysql://192.168.1.48:3306/core?seUnicode=true&characterEncoding=UTF-8}"
      username: "root"
      password: "root.R7db@192.168.1.48"
      driver-class-name: "com.mysql.cj.jdbc.Driver"

  redis:
    host: 192.168.1.48
    port: 6379

mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml

agora:
  appId: c02f35742ed94202b4b8fe2f91101da6
  appCertificate: 6d900e3978e44155b4dc360546eaf67e
  # token过期时间
  expirationTimeInSeconds: 360
  # true：启用混合录制  false：关闭混合录制
  isMixingEnabled: true
  #MIXED_AV_DEFAULT 0：（默认）不混合音频和视频。
  #MIXED_AV_CODEC_V1 1：音频和视频混合成一个文件，录制文件格式为 MP4，但播放器支持有限。
  #MIXED_AV_CODEC_V2 2：音频和视频混合成一个文件，录制文件格式为 MP4，支持更多播放器。
  mixedVideoAudio: 2
  subscribeAudioUids: 1
  subscribeVideoUids: 1
  layoutMode: 2
  # 最低的UDP端口。确保highUdpPort的值-lowUdpPort≥6
  lowUdpPort: 40000
  # 最高的UDP端口。确保highUdpPort的值-lowUdpPort≥6
  highUdpPort: 41000
  # 设置AgoraCoreService的路径
  appliteDir: /root/data/apps
  recordFileRootDir: /root/stand_video/stand_video
  # 日志级别
  # FATAL(1),
  # ERROR(2),
  # WARNING(3),
  # NOTICE(4),
  # INFO(5),
  # DEBUG(6);
  logLevel: 5
  agoraLib: /root/data/apps/librecording.so

