server:
  port: 8098
  servlet:
    context-path: /api

spring:
  application:
    name: stand-video
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.49:8848
        namespace: d685bf52-93ce-4271-942b-688f25725547

  datasource:
    druid:
      url: jdbc:mysql://192.168.1.48:3306/core?seUnicode=true&characterEncoding=UTF-8}
      username: "root"
      password: "root.R7db@192.168.1.48"
      driver-class-name: "com.mysql.cj.jdbc.Driver"

  redis:
    host: 192.168.1.48
    port: 6379

mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml

agora:
  appId: b2fc1118e42c419da44802375a2508bd
  appCertificate: 1a98cbaafff74b4eb6714a772c97a149
  # token过期时间
  expirationTimeInSeconds: 86400
  # 设置空闲频道的超时退出时间。默认值为 300 秒。
  idleLimitSec: 3
  # true：启用混合录制  false：关闭混合录制
  isMixingEnabled: true
  #MIXED_AV_DEFAULT 0 默认）不混合音频和视频。
  #MIXED_AV_CODEC_V1 1音频和视频混合成一个文件，录制文件格式为 MP4，但播放器支持有限。
  #MIXED_AV_CODEC_V2 2音频和视频混合成一个文件，录制文件格式为 MP4，支持更多播放器。
  mixedVideoAudio: MIXED_AV_CODEC_V2
  #格式为：width，hight，fps，kbps，分别对应合流的宽、高、帧率和码率。
  mixResolution: "360,640,15,500"
  autoSubscribe: false
  # 最低的UDP端口。确保highUdpPort的值-lowUdpPort≥6
  lowUdpPort: 40000
  # 最高的UDP端口。确保highUdpPort的值-lowUdpPort≥6
  highUdpPort: 41000
  # 设置AgoraCoreService的路径
  appliteDir: /root/data/stand_video_backup
  recordFileRootDir: /root/data/stand_video_backup/stand_video_data
  # 日志级别
  # FATAL(1),
  # ERROR(2),
  # WARNING(3),
  # NOTICE(4),
  # INFO(5),
  # DEBUG(6);
  logLevel: 6
  agoraLib: /root/data/stand_video_backup/librecording.so


resource:
  address: "http://192.168.1.50:8099/api/file"

